/*
 *      File: DesplazamientoInDTO.java
 *    Author: Orlando Ramos <orlando.ramos@root.com.mx>
 *      Date: Oct 14, 2017
 * Copyright: Root Technologies, S.A. de C.V. 2017
 */

package com.mx.root.sintec.model.dto;

/**
 *  Objeto que recibe {@link  com.mx.root.sintec.controller.DesplazamientoInventarioController#getReport(DesplazamientoInDTO)}.
 *  Este objeto contiene los campos usados como filtros para obtener la información.
 * @author Orlando Ramos &lt;orlando.ramos@root.com.mx&gt;
 * @version 1.0.0
 * @since 1.0.0
 */
public class DesplazamientoInDTO {

    /**
     * Id del departamento.
     */
    private Integer idDepartamento;
    /**
     * Id del sub departamento.
     */
    private Integer idSubdepartamento;

    /**
     * Getter for idDepartamento.
     * @return idDepartamento.
     **/
    public Integer getIdDepartamento() {
        return idDepartamento;
    }

    /**
     * Setter for idDepartamento.
     * @param idDepartamento expected.
     **/
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    /**
     * Getter for idSubdepartamento.
     * @return idSubdepartamento.
     **/
    public Integer getIdSubdepartamento() {
        return idSubdepartamento;
    }

    /**
     * Setter for idSubdepartamento.
     * @param idSubdepartamento expected.
     **/
    public void setIdSubdepartamento(Integer idSubdepartamento) {
        this.idSubdepartamento = idSubdepartamento;
    }

    /**
     * Mètodo para validar la igualdad entre ojbetos de tipo {@link DesplazamientoInDTO}
     * @param o Objeto a comparar.
     * @return Es igual = true , No es ifual = false:
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DesplazamientoInDTO)) return false;

        DesplazamientoInDTO that = (DesplazamientoInDTO) o;
        // autogenerated
        if (!getIdDepartamento().equals(that.getIdDepartamento())) return false;
        return getIdSubdepartamento().equals(that.getIdSubdepartamento());
    }

    @Override
    public int hashCode() {
        int result = getIdDepartamento().hashCode();
        result = 31 * result + getIdSubdepartamento().hashCode();
        return result;
    }

    /**
     * Imprimer el objeto.
     * @return Un {@link String} con un formato legible para el usuario.
     */
    @Override
    public String toString() {
        return "DesplazamientoInDTO{" +
                "idDepartamento=" + idDepartamento +
                ", idSubdepartamento=" + idSubdepartamento +
                '}';
    }
}
